spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [client id]
            client-secret: [client secret]
            scope: profile,email
          # naver와 kakao는 Spring security에 provider가 존재하지 않아서 정의가 필요
          naver:
            client-id: [client id]
            client-secret: [client secret]
            scope: profile,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          kakao:
            client-id: [client id]
            client-secret: [client secret]
            client-scope: profile,email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id