spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [client id]
            client-secret: [client secret]
            scope: profile,email
          # naver와 kakao는 Spring security에 provider가 존재하지 않아서 정의가 필요
          naver:
            client-id: [client id]
            client-secret: [client secret]
            scope: profile,email,name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response